language: generic
matrix:
  include:
    - language: generic
      sudo: required
      services:
        - docker
      before_install:
        - docker pull greenaddress/android_cordova
      script: docker run -v $PWD:/walletcordova greenaddress/android_cordova

    - os: osx
      osx_image: xcode8.3
      before_script: sudo npm install -g cordova
      sudo: required
      install:
        - brew update > /dev/null
        - brew upgrade node
        - pip install virtualenv
      script:
        - ./prepare.sh
        - cordova prepare ios
        - cordova build ios

